# Generated by Django 6.0.6 on 2026-08-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaloryCounterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='heigth',
            new_name='height',
        ),
    ]
